# Generated by Django 5.2.8 on 2025-11-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_crear_datos_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaPosMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pruebalaboratorio',
            name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='sintoma',
            name='enfermedades',
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='pruebas_lab',
            field=models.ManyToManyField(blank=True, related_name='enfermedades', to='gestion.pruebalaboratorio'),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='sintomas',
            field=models.ManyToManyField(blank=True, related_name='enfermedades', to='gestion.sintoma'),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='pruebas_postmortem',
            field=models.ManyToManyField(blank=True, related_name='enfermedades', to='gestion.pruebaposmortem'),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='signos',
            field=models.ManyToManyField(blank=True, related_name='enfermedades', to='gestion.signo'),
        ),
    ]
